Refactor compose ymls, ensure 'dc down' runs regardless of test failures

diff --git a/bin/docker_tests b/bin/docker_tests
--- a/bin/docker_tests
+++ b/bin/docker_tests
@@ -9,7 +9,12 @@ cd "${0%/*}/.."
 
 echo "Running tests"
 
-bin/dc up -d
+# Always run dc down regardless of success/failure
+trap 'bin/dc down' EXIT
+
+export ROLE=test
+
+bin/dc up -d --remove-orphans
 
 bin/dc exec -T runserver /bin/bash -c '! poetry install --dry-run | grep "Warning: The lock file is not up to date" || (echo "poetry.lock does not match pyproject.toml" && exit 1)'
 
@@ -28,5 +33,3 @@ bin/dc exec -T runserver bandit -r apps
 bin/dc exec -T runserver pytest -p no:cacheprovider --cov=apps --cov-config=.coveragerc --cov-report= tests/profiles-enabled
 
 bin/dc exec -T runserver pytest -p no:cacheprovider --cov=apps --cov-config=.coveragerc --cov-append --ds=conf.test_settings_profiles_disabled tests/profiles-disabled
-
-bin/dc down
